#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 4th iteration, displays "bad luck" on the 8th iteration "good luck".
#  otherwise displays 'Best school' for all the other iterations

count=0

while [ $count -lt 10 ]

do

  if [ $count -eq 4 ]

  then

    echo "bad luck"

  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best school"
  fi
  (( count++ ))

done
